# Uncomment this line to define a global platform for your project
 platform :ios, '8.0'
# Uncomment this line if you're using Swift
 use_frameworks!

target 'MyBrowser' do

pod 'AFNetworking'
pod 'hpple'
pod 'JDStatusBarNotification'
pod 'CWFoundation', :git => 'https://github.com/guojiubo/CWFoundation.git', :commit => '2352449291499091f4e4a82877ec57c9070ced35'
pod 'CWStackController', :git => 'https://github.com/guojiubo/CWStackController.git', :commit => '8ff182c2f4e6b4cc31b9357f2a31f6bde456ef87'
pod 'CocoaLumberjack', '1.9.2'
pod 'FMDB'
pod 'pop'
pod 'FLAnimatedImage'
pod 'RunTrace'
pod 'ReactiveCocoa', '~> 4.0.4-alpha-4'

end

target 'MyBrowserTests' do

end

target 'MyBrowserUITests' do

end

